### ISSUE TITLE
Should bundle vnu-validator

### ISSUE THREAD

**Issue by zoomorph** [shlomif/python-vnu_validator#3]
Would be more useful if this package bundled vnu-validator, similar to the closure package for example: https://pypi.org/project/closure/

**Comment by shlomif** [comment]
@zoomorph : I disagree because:

1. It will increase the download size.

2. Will require updating the pypi package based on the java code.

3. Will be a problem if the user already has the java code installed.

----

Note that you can create a separate package similar to https://metacpan.org/pod/Alien::Libxml2 and similar that  will install the validator or wrap my module. I'll integerate it with https://github.com/shlomif/python-vnu_validator if I find it good enough.

**Comment by shlomif** [comment]
@zoomorph : can I close this bug?

**Comment by shlomif** [comment]
@zoomorph : closing as WONTFIX
